Library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('customer_login/', views.CustomerLoginView.as_view(), name='customer_login'),
    path('customer_signup/', views.CustomerSignUpView.as_view(), name='customer_signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('email_book/', views.send_email, name='email_book'),
    path('book/<uuid:pk>/return', views.return_book, name='return_book'),
    path('book/<uuid:pk>/borrow/', views.borrow_book, name='borrow_book'),
    path('dashboard_customer/', views.LoanedBooksByUserListView.as_view(), name='dashboard_customer'),
    path('dashboard_staff/', views.LoanedBooksAllListView.as_view(), name='dashboard_staff'),
    path('search_book/', views.BookSearchListView.as_view(), name='search_book'),
    path('search_author/', views.AuthorSearchListView.as_view(), name='search_author'),
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

mylibrary/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add paths from the catalog application 
from django.urls import include
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
import uuid
from datetime import date

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField(max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    picture = models.ImageField(upload_to='book_images/%Y/%m/%d/', null=True, blank=True, default='book_images/no_profile_picture.png')
    file = models.FileField(upload_to='book_pdf/%Y/%m/%d/', null=True, blank=True, default='book_pdf/no_pdf.pdf')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    class Meta:
        ordering = ['title']


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    STATUS_MAINTENANCE = 'm'
    STATUS_ON_LOAN = 'o'
    STATUS_AVAILABLE = 'a'
    STATUS_RESERVED = 'r'

    LOAN_STATUS = (
        (STATUS_MAINTENANCE, 'Maintenance'),
        (STATUS_ON_LOAN, 'On loan'),
        (STATUS_AVAILABLE, 'Available'),
        (STATUS_RESERVED, 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default=STATUS_MAINTENANCE,
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"), ("can_create_book", "Create new book"), ("can_update_book", "Update book details"), ("can_delete_book", "Delete book"),)


    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)
    author_profile_picture = models.ImageField(upload_to='author_images/%Y/%m/%d/', null=True, blank=True, default='author_images/no_image.png')

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['last_name', 'first_name']
        permissions = (("can_create_author", "Create new author"), ("can_update_author", "Update author details"), ("can_delete_author", "Delete author"),)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profile_picture = models.ImageField(upload_to='customer_profile_images/%Y/%m/%d/', null=True, blank=True,
                                        verbose_name="Profile Picture", default='author_images/no_image.png')
    phone_number = models.CharField(null=True, blank=True, max_length=10)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
import datetime
from catalog.models import BookInstance


class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views.py
import operator
import smtplib
from functools import reduce
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.mixins import PermissionRequiredMixin
from catalog.models import Author, Book, BookInstance, Profile
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.views.generic import View
from django.core.mail.message import EmailMessage
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import permission_required
from catalog.forms import RenewBookModelForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
STATUS_MAINTENANCE = 'm'
STATUS_ON_LOAN = 'o'
STATUS_AVAILABLE = 'a'
STATUS_RESERVED = 'r'


def index(request):
        num_books = Book.objects.all().count()
        num_instances = BookInstance.objects.all().count()
        num_instances_available = BookInstance.objects.filter(status__exact='a').count()
        num_authors = Author.objects.count()
        # Number of visits to this view, as counted in the session variable.
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1

        context = {
            'num_books': num_books,
            'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_authors': num_authors,
            'num_visits': num_visits,
        }
        return render(request, 'catalog/index.html', context=context)


@method_decorator(login_required, 'dispatch')
class BookListView(generic.ListView):
    model = Book
    paginate_by = 3


@method_decorator(login_required, 'dispatch')
class BookDetailView(generic.DetailView):
    model = Book


# @method_decorator(login_required, 'dispatch')
class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 3
    template_name = 'catalog/author_list.html'


@method_decorator(login_required, 'dispatch')
class AuthorDetailView(generic.DetailView):
    model = Author


class CustomerLoginView(View):
    def post(self, request):
        username_r = request.POST['customer_username']
        password_r = request.POST['customer_password']

        user = authenticate(request, username=username_r, password=password_r)

        if user is not None:
            login(request, user)
            if user.is_staff:
                return HttpResponseRedirect(reverse('dashboard_staff', args=[]))
            else:
                return HttpResponseRedirect(reverse('dashboard_customer', args=[]))
        else:
            return HttpResponseRedirect(reverse('customer_login'))

    def get(self, request):
        return render(request, 'catalog/customer_login.html')


class CustomerSignUpView(View):
    def post(self, request):
        name_r = request.POST.get('customer_username')
        password_r = request.POST.get('customer_password')
        email_r = request.POST.get('customer_email')

        contact_number_r = request.POST.get('customer_contact_number')
        profile_picture_r = request.POST.get('customer_profile_picture')

        if checkemail(email_r):
            c = User.objects.create_user(username=name_r, password=password_r, email=email_r)
            c.save()

            p = Profile(user=c, phone_number=contact_number_r, profile_picture=profile_picture_r)
            p.save()

            return render(request, 'catalog/customer_login.html')
        else:
            return render(request, 'catalog/customer_signup.html')

    def get(self, request):
        return render(request, 'catalog/customer_signup.html')


def checkemail(email_r):
    try:
        validate_email(email_r)
    except ValidationError:
        False
    return True


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


def send_email(request):
    if request.user.is_authenticated:
        send_to = request.user.email
        username = request.user.username

    book = Book.objects.get(pk=int(request.POST.get('book_id')))
    book_title = str(book.title)
    book_author = str(book.author)
    book_pdf = book.file.path

    email_body = "Hello "+username+"\n\n Please find attachment your requested PDF file below \n\n Book: "+book_title+"\n Book Author: "+book_author+"\n\n"

    try:
        # send_mail('Book request', email_body, settings.EMAIL_HOST_USER, ['madhok.simran8@gmail.com'], fail_silently=False)
        email = EmailMessage(
            'Library Book request',
            email_body,
            'sender smtp gmail' + '<dolphin2016water@gmail.com>',
            [send_to],
        )
        email.attach_file(book_pdf, mimetype='application/pdf')
        email.send()
    except smtplib.SMTPException:
        return HttpResponseRedirect(reverse('index'))

    return HttpResponseRedirect(reverse('dashboard_customer', args=[]))


def borrow_book(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
            if request.user.is_authenticated:
                book_instance.borrower = request.user
                book_instance.due_back = datetime.date.today() + datetime.timedelta(weeks=3)
                book_instance.status = STATUS_ON_LOAN
                book_instance.save()
                return HttpResponseRedirect(reverse('dashboard_customer'))

    context = {
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_detail.html', context)


# @method_decorator(login_required, 'dispatch')
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/dashboard_customer.html'

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/dashboard_staff.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk = pk)
    if request.method == 'POST':
        form = RenewBookModelForm(request.POST)
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()
            return HttpResponseRedirect(reverse('dashboard_staff'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

def return_book(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    book_instance.status = STATUS_AVAILABLE
    book_instance.save()
    return HttpResponseRedirect(reverse('dashboard_customer'))


class AuthorCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'can_create_author'
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('authors')


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'can_update_author'
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    success_url = reverse_lazy('authors')


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'can_delete_author'
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_create_book'
    success_url = reverse_lazy('books')


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_update_book'
    success_url = reverse_lazy('books')


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    permission_required = 'catalog.can_delete_book'
    success_url = reverse_lazy('books')


class BookSearchListView(BookListView):
    paginate_by = 3

    def get_queryset(self):
        result = super(BookSearchListView, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(title__icontains=q) for q in query_list))
            )

        return result


class AuthorSearchListView(AuthorListView):
    paginate_by = 3

    def get_queryset(self):
        result = super(AuthorSearchListView, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(first_name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(last_name__icontains=q) for q in query_list))
            )

        return result

catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <div class="container" style="margin-top: 50px">
        <h3 style="font-family: 'Times New Roman';">Delete Author</h3><hr><br><br>
        <p style="font-family: 'Times New Roman';">Are you sure you want to delete the author: {{ author }}?</p>

        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn btn-danger">
             <a href="{% url 'dashboard_staff' %}"><input type="button" value="Cancel" class="btn btn-info"></a>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <div class="container" style="margin-top: 40px">
        <div style="margin-left: 35px">
        <form action="{% url 'search_author' %}" method="get">
            <div class="form-group row">
                <input type="submit" value="Search" class="btn btn-primary active col-sm-1" >
                <div class="col-sm-5">
                    <input type="text" name="q" class="form-control" style="background: none; font-family: 'Times New Roman'" placeholder="Search author by name i.e Marcel">
                </div>
            </div>
        </form><br><br>
        </div>
        {% if author_list %}
            <div class="card-group">
                {% for author in author_list %}
                    <div class="card col-md-4">
                        <a href="{{author.get_absolute_url}}"><img class="card-img-top img-fluid" src="{{ author.author_profile_picture.url }}" alt="Card image cap" height="250px"></a>
                        <div class="card-body">
                            <a href="{{author.get_absolute_url}}"><h5 class="card-footer" style="font-family: Kefa;">{{ author.first_name }} {{ author.last_name }}</h5></a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <div class="container" style="margin-top: 50px">
        {% if user.is_staff %}
        <div class="row">
            <div class="col-sm-8">
                <label style="font-family: 'Times New Roman'">Book Title: {{ book.title }}</label>
                <p><strong style="font-family: 'Times New Roman'">Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
                <p><strong style="font-family: 'Times New Roman'">Summary:</strong> <label style="font-family: 'Times New Roman'">{{ book.summary }}</label></p>
                <p><strong style="font-family: 'Times New Roman'">ISBN:</strong> {{ book.isbn }}</p>
                <p><strong style="font-family: 'Times New Roman'">Genre:</strong>
                    {% for genre in book.genre.all %}
                        {{ genre }}
                        {% if not forloop.last %},
                        {% endif %}
                    {% endfor %}
                </p>
            </div>
            <div class="col-sm-4">
                <img src="{{ book.picture.url }}" height="300px">
            </div>
        </div>

        <div style="margin-left:10px;margin-top:10px">
            <strong><h4 style="font-family: 'Times New Roman'">Copies</h4></strong>

            {% for copy in book.bookinstance_set.all %}
                <hr>
                <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
                {% if copy.status != 'a' %}
                    <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
                {% endif %}
                <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
            {% endfor %}
        </div>

        {% else %}

        <div class="row">
            <div class="col-sm-8">
                <label style="font-family: 'Times New Roman'">Book Title: {{ book.title }}</label>
                <p><strong style="font-family: 'Times New Roman'">Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
                <p><strong style="font-family: 'Times New Roman'">Summary:</strong> <label style="font-family: 'Times New Roman'">{{ book.summary }}</label></p>
                <p><strong style="font-family: 'Times New Roman'">ISBN:</strong> {{ book.isbn }}</p>
                <p><strong style="font-family: 'Times New Roman'">Genre:</strong>
                    {% for genre in book.genre.all %}
                        {{ genre }}
                        {% if not forloop.last %},
                        {% endif %}
                    {% endfor %}
                </p>
                <p>
                    <strong style="font-family: 'Times New Roman'">Download</strong>&nbsp;<a href="{{ book.file.url }}"><span class="glyphicon glyphicon-download-alt"></span></a>&nbsp;&nbsp;
                    <form method="POST" action ="{% url 'email_book' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="book_id" value="{{ book.id }}">
                        <strong style="font-family: 'Times New Roman'">Send me a copy</strong>&nbsp;<button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;Email</button><br><br>
                    </form>
                    {% for copy in book.bookinstance_set.all %}
                        {% if copy.status == 'a' %}
                            <form method="POST" action ="{% url 'borrow_book' copy.id %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-book"></span>&nbsp;&nbsp;Borrow the book</button>
                            </form>
{#                        {% else %}#}
{#                            <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-book"></span>&nbsp;&nbsp;Book unavailable</button>#}
                        {% endif %}
                    {% endfor %}
                </p>
            </div>
            <div class="col-sm-4">
                <img src="{{ book.picture.url }}" height="300px">
            </div>
        </div>
        {% endif %}
    </div>

{% comment %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}{% endcomment %}

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/dashboard_customer.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <div class="container" style="margin-top: 50px">
        <h3 style="font-family: 'Times New Roman';">Borrowed books</h3><br>

        {% if bookinstance_list %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="font-family: 'Times New Roman'">Book</th>
                        <th scope="col" style="font-family: 'Times New Roman'">Due Back</th>
                        <th scope="col" style="font-family: 'Times New Roman'">Return Book</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bookinst in bookinstance_list %}
                    <tr>
                        <td style="font-family: 'Times New Roman'"><a href="{% url 'book-detail' bookinst.book.pk %}" >{{bookinst.book.title}}</a></td>
                        {% if bookinst.is_overdue%}
                            <td style="font-family: 'Times New Roman'; color: red;">{{ bookinst.due_back }}</td>
                        {% else %}
                            <td style="font-family: 'Times New Roman';">{{ bookinst.due_back }}</td>
                        {% endif %}
                        <td style="font-family: 'Times New Roman'"><a href="{% url 'return_book' bookinst.id %}"><span class="glyphicon glyphicon-new-window"></span></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% else %}
            <p style="font-family: 'Times New Roman';">There are no books borrowed.</p>
        {% endif %}
    </div>
{% endblock %}

{% comment %} {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}{% endcomment %}

catalog/templates/catalog/dashboard_staff.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <div class="container" style="margin-top: 50px">
        <h3 style="font-family: 'Times New Roman'; float:left;">Books borrowed</h3>
        {% if user.is_superuser %}
            <a href="{% url 'book_create' %}"><button type="button" class="btn btn-primary" style="float: right"><span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Add Book</button></a>
            <a href="{% url 'author_create' %}"><button type="button" class="btn btn-primary" style="float: right"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Add Author</button></a>
            <br><br>
        {% endif %}
        {% if bookinstance_list %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="font-family: 'Times New Roman'">Book</th>
                        <th scope="col" style="font-family: 'Times New Roman'">Due Back</th>
                        <th scope="col" style="font-family: 'Times New Roman'">Renew</th>
                        {% if perms.catalog.can_update_book %}
                            <th scope="col" style="font-family: 'Times New Roman'">Update Book</th>
                        {% endif %}
                        {% if perms.catalog.can_delete_book %}
                            <th scope="col" style="font-family: 'Times New Roman'">Delete Book</th>
                        {% endif %}
                        {% if perms.catalog.can_update_author %}
                            <th scope="col" style="font-family: 'Times New Roman'">Update Author</th>
                        {% endif %}
                        {% if perms.catalog.can_delete_author %}
                            <th scope="col" style="font-family: 'Times New Roman'">Delete Author</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for bookinst in bookinstance_list %}
                    <tr>
                        <td style="font-family: 'Times New Roman'"><a href="{% url 'book-detail' bookinst.book.pk %}" >{{bookinst.book.title}}</a></td>
                        {% if bookinst.is_overdue%}
                            <td style="font-family: 'Times New Roman'; color: red;">{{ bookinst.due_back }}</td>
                        {% else %}
                            <td style="font-family: 'Times New Roman'">{{ bookinst.due_back }}</td>
                        {% endif %}
                        {% if perms.catalog.can_mark_returned %}
                            <td style="font-family: 'Times New Roman'"><a href="{% url 'renew-book-librarian' bookinst.id %}"><span class="glyphicon glyphicon-repeat"></span></a></td>
                        {% endif %}
                        {% if perms.catalog.can_update_book %}
                            <td style="font-family: 'Times New Roman'"><a href="{% url 'book_update' bookinst.book_id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                        {% endif %}
                        {% if perms.catalog.can_delete_book %}
                            <td style="font-family: 'Times New Roman'"><a href="{% url 'book_delete' bookinst.book_id %}"><button class="btn btn-danger">Delete</button></a></td>
                        {% endif %}
                        {% if perms.catalog.can_update_author %}
                            <td style="font-family: 'Times New Roman'"><a href="{% url 'author_update' bookinst.book.author.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                        {% endif %}
                        {% if perms.catalog.can_delete_author %}
                            <td style="font-family: 'Times New Roman'"><a href="{% url 'author_delete' bookinst.book.author.pk %}"><button class="btn btn-danger">Delete</button></a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% else %}
            <p style="font-family: 'Times New Roman';">There are no books borrowed.</p>
        {% endif %}
    </div>
{% endblock %}